apiVersion: v1
kind: Service
metadata:
  labels:
    app: techtrends
    tag: latest
  name: techtrends
  namespace: sandbox
spec:
  type: ClusterIP
  selector:
    app: techtrends
    tag: latest
  ports:
  - port: 4111
    targetPort: 3111
    protocol: TCP