namespace:
  name: prod

service:
  type: ClusterIP
  port: 7111
  targetPort: 3111
  protocol: TCP

image:
  repository: techtrends
  tag: latest
  pullPolicy: Always

replicaCount: 5

resources:
  requests:
    cpu: 350m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

containerPort: 3111

livenessProbe:
  path: /healthz
  port: 3111
readinessProbe:
  path: /healthz
  port: 3111